### ISSUE TITLE
在NODE4下必须要使用use strict才能使用局部变量的语法-部署报错

### ISSUE THREAD

**Issue by 1166544** [fex-team/fis-deploy-default#1]
在NODE4下必须要使用use strict才能使用局部变量的语法，现在我们部署的时候报了这个错误

[ERROR] load plugin [fis-deploy-default] error : Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

求解决

**Comment by mingxuWang** [comment]
我也遇到这个问题了，现在都无法正常部署成功。

**Comment by 2betop** [comment]
已收到反馈，下午修复！
